# Generated by Django 5.0.3 on 2024-03-18 17:41

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', encrypted_model_fields.fields.EncryptedCharField()),
                ('last_name', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
    ]
